# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
    apt-get install -y libpq-dev && \
    pip install --no-cache-dir -r requirements.txt \
    && pip install psycopg2-binary  # Install psycopg2 \
    && pip install beautifulsoup4

# Initialize the Airflow database
RUN airflow db init

# Set environment variables for user creation
ENV AIRFLOW_USERNAME=admin
ENV AIRFLOW_FIRSTNAME=admin
ENV AIRFLOW_LASTNAME=user
ENV AIRFLOW_ROLE=Admin
ENV AIRFLOW_EMAIL=yashchamp96@gmail.com
ENV AIRFLOW_PASSWORD=adminpassword

# Create an Airflow user
RUN airflow users create \
    --role ${AIRFLOW_ROLE} \
    --username ${AIRFLOW_USERNAME} \
    --firstname ${AIRFLOW_FIRSTNAME} \
    --lastname ${AIRFLOW_LASTNAME} \
    --email ${AIRFLOW_EMAIL} \
    --password ${AIRFLOW_PASSWORD}

# Expose the web server port
EXPOSE 8080

# Start the Airflow web server
CMD ["airflow", "webserver", "--port", "8080"]

